### ISSUE TITLE
Just started getting an error "TypeError: Cannot read property 'processIncomingMessage' of undefined"

### ISSUE THREAD

**Issue by jaytay79** [KraigM/homebridge-nest#110]
I have just updated to the latest version of homebridge and I have just started getting the below error when trying to start it up again. Any ideas?

/usr/lib/node_modules/homebridge-nest/node_modules/firebase/node_modules/faye-websocket/node_modules/websocket-driver/node_modules/websocket-extensions/lib/websocket_extensions.js:133
    this._pipeline.processIncomingMessage(message, callback, context);
                  ^

TypeError: Cannot read property 'processIncomingMessage' of undefined
    at Extensions.processIncomingMessage (/usr/lib/node_modules/homebridge-nest/node_modules/firebase/node_modules/faye-websocket/node_modules/websocket-driver/node_modules/websocket-extensions/lib/websocket_extensions.js:133:19)
    at Client._emitMessage (/usr/lib/node_modules/homebridge-nest/node_modules/firebase/node_modules/faye-websocket/node_modules/websocket-driver/lib/websocket/driver/hybi.js:442:22)
    at Client._emitFrame (/usr/lib/node_modules/homebridge-nest/node_modules/firebase/node_modules/faye-websocket/node_modules/websocket-driver/lib/websocket/driver/hybi.js:405:19)
    at Client.parse (/usr/lib/node_modules/homebridge-nest/node_modules/firebase/node_modules/faye-websocket/node_modules/websocket-driver/lib/websocket/driver/hybi.js:144:18)
    at Client.parse (/usr/lib/node_modules/homebridge-nest/node_modules/firebase/node_modules/faye-websocket/node_modules/websocket-driver/lib/websocket/driver/client.js:56:58)
    at IO.write (/usr/lib/node_modules/homebridge-nest/node_modules/firebase/node_modules/faye-websocket/node_modules/websocket-driver/lib/websocket/streams.js:80:16)
    at TLSSocket.ondata (_stream_readable.js:555:20)
    at emitOne (events.js:96:13)
    at TLSSocket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at TLSSocket.Readable.push (_stream_readable.js:134:10)
    at TLSWrap.onread (net.js:548:20)

**Comment by rtoohil** [comment]
See issues 106 and 107. It's an issue with the websocket driver. I've committed a pull request that has a work around, but you'll find a couple of different fix options in those above issues.

**Comment by mmaxwell5** [comment]
I am having the same issue.  I tried updating the websocket driver but when I start homebridge it just gets stuck when it gets to the loading my nest devices.  I do not get an error.  when I remove the nest plugin homebridge starts and my other devices work fine.  Any help would be greatly appreciated.  Thank you.

**Comment by mountfords** [comment]
I'm having a similar issue. Ive not changed anything on the system but it will not load the nest device any longer.

_[1/15/2017, 9:06:56 PM] Fetching Nest devices.
[1/15/2017, 9:06:56 PM] Loading 0 accessories...
/usr/local/lib/node_modules/homebridge-nest/node_modules/firebase/node_modules/faye-websocket/node_modules/websocket-driver/node_modules/websocket-extensions/lib/websocket_extensions.js:133
    this._pipeline.processIncomingMessage(message, callback, context);
                  ^

TypeError: Cannot read property 'processIncomingMessage' of undefined
    at Extensions.processIncomingMessage (/usr/local/lib/node_modules/homebridge-nest/node_modules/firebase/node_modules/faye-websocket/node_modules/websocket-driver/node_modules/websocket-extensions/lib/websocket_extensions.js:133:19)
    at Client._emitMessage (/usr/local/lib/node_modules/homebridge-nest/node_modules/firebase/node_modules/faye-websocket/node_modules/websocket-driver/lib/websocket/driver/hybi.js:442:22)_

**Comment by mewejo** [comment]
Me too, same error messages, only just started happening yesterday.

Something else to note, Skylark is unable to update my Nest too. Skylark doesn't interface with Homebridge at all, and is also having Nest API issues, suspect something has changed on their end.

**Comment by BlaydeRunner08** [comment]
I'm also having the same issue.

I've tried the solution @smolyneux mentions in #107 , but I now just get a hanging homebridge, which never fully initializes

**Comment by mewejo** [comment]
Getting the same as @BlaydeRunner08. I updated that module but now it just hangs here:

> [1/17/2017, 10:59:08 PM] Fetching Nest devices.
[1/17/2017, 10:59:08 PM] Loading 0 accessories...

**Comment by omarshahine** [comment]
I'm getting the hang as well. Tried all the solutions posted here to no avail.

**Comment by mmaxwell5** [comment]
Without changing anything on my home bridge server it started working for me again. Weird... certainly feels like an issue on nest's end but not 100% sure.

**Comment by mewejo** [comment]
Me too, all of a sudden started working again. This is with the patch. Agree with feels like a Nest API issue.

**Comment by mmaxwell5** [comment]
It crashed again.  Back to legacy API.
