### ISSUE TITLE
SyntaxError: Unexpected token ]

### ISSUE THREAD

**Issue by jbhul** [KraigM/homebridge-nest#114]
Hello All

I am running home bridge with Nest on a Raspberry Pi and I get the error 

[1/24/2017, 2:35:43 AM] Loaded plugin: homebridge-nest
[1/24/2017, 2:35:43 AM] Registering platform 'homebridge-nest.Nest'
[1/24/2017, 2:35:43 AM] ---
[1/24/2017, 2:35:43 AM] There was a problem reading your config.json file.
[1/24/2017, 2:35:43 AM] Please try pasting your config.json file here to validate it: http://jsonlint.com
[1/24/2017, 2:35:43 AM]
/usr/local/lib/node_modules/homebridge/lib/server.js:197
    throw err;
    ^

SyntaxError: Unexpected token ]
    at Object.parse (native)
    at Server._loadConfig (/usr/local/lib/node_modules/homebridge/lib/server.js:191:19)
    at new Server (/usr/local/lib/node_modules/homebridge/lib/server.js:52:38)
    at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:26:16)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (module.js:434:26)
    at Object.Module._extensions..js (module.js:452:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:475:10)
    at startup (node.js:117:18)
    at node.js:951:3

  This is my config:
`{
    "bridge": {
        "name": "Homebridge",
        "username": "CC:22:3D:E3:CE:30",
        "port": 51826,
        "pin": "031-45-154"
    },
    
    "description": "This is an example configuration file with one fake accessory and one fake platform. You can use this as a template for creating your own configuration file containing devices you actually own.",

    "platforms": [
        {
            "platform": "Nest",

            "clientId": "Actual ID",
            "clientSecret": "Its a secret",
            "code": "The Code",

            "username" : "username",
            "password" : "password"
        },
    ],
}`

id, secret, and code have been changed but uname and pass are actually that.
TIA

**Comment by igbopie** [comment]
There is an extra comma at the end of platforms.
