### ISSUE TITLE
Error after updating Homebridge to 0.4.23

### ISSUE THREAD

**Issue by Krocko** [KraigM/homebridge-nest#131]
I have updated Homebridge to 0.4.23. Now I got the following error.

```
Aug 15 08:11:06 raspberrypi homebridge[21855]: at NestProtectAccessory.NestDeviceAccessory.bindCharacteristic (/usr/local/lib/node_modules/homebridge-nest/lib/nest-device-accessory.js:65:9)
Aug 15 08:11:06 raspberrypi homebridge[21855]: at NestProtectAccessory.NestDeviceAccessory (/usr/local/lib/node_modules/homebridge-nest/lib/nest-device-accessory.js:52:10)
Aug 15 08:11:06 raspberrypi homebridge[21855]: at new NestProtectAccessory (/usr/local/lib/node_modules/homebridge-nest/lib/nest-protect-accessory.js:41:25)
Aug 15 08:11:06 raspberrypi homebridge[21855]: at NestPlatform.<anonymous> (/usr/local/lib/node_modules/homebridge-nest/index.js:118:23)
Aug 15 08:11:06 raspberrypi homebridge[21855]: at NestPlatform.<anonymous> (/usr/local/lib/node_modules/homebridge-nest/index.js:126:4)
Aug 15 08:11:06 raspberrypi homebridge[21855]: at /usr/local/lib/node_modules/homebridge-nest/index.js:153:28
Aug 15 08:11:06 raspberrypi homebridge[21855]: at tryCatcher (/usr/local/lib/node_modules/homebridge-nest/node_modules/bluebird/js/release/util.js:16:23)
Aug 15 08:11:06 raspberrypi homebridge[21855]: at Promise._settlePromiseFromHandler (/usr/local/lib/node_modules/homebridge-nest/node_modules/bluebird/js/release/promise.js:512:31)
Aug 15 08:11:06 raspberrypi homebridge[21855]: at Promise._settlePromise (/usr/local/lib/node_modules/homebridge-nest/node_modules/bluebird/js/release/promise.js:569:18)
Aug 15 08:11:06 raspberrypi homebridge[21855]: at Promise._settlePromise0 (/usr/local/lib/node_modules/homebridge-nest/node_modules/bluebird/js/release/promise.js:614:10)
Aug 15 08:11:06 raspberrypi homebridge[21855]: at Promise._settlePromises (/usr/local/lib/node_modules/homebridge-nest/node_modules/bluebird/js/release/promise.js:693:18)
Aug 15 08:11:06 raspberrypi homebridge[21855]: at Async._drainQueue (/usr/local/lib/node_modules/homebridge-nest/node_modules/bluebird/js/release/async.js:133:16)
Aug 15 08:11:06 raspberrypi homebridge[21855]: at Async._drainQueues (/usr/local/lib/node_modules/homebridge-nest/node_modules/bluebird/js/release/async.js:143:10)
Aug 15 08:11:06 raspberrypi homebridge[21855]: at Immediate.Async.drainQueues (/usr/local/lib/node_modules/homebridge-nest/node_modules/bluebird/js/release/async.js:17:14)
Aug 15 08:11:06 raspberrypi homebridge[21855]: at runCallback (timers.js:781:20)
Aug 15 08:11:06 raspberrypi homebridge[21855]: at tryOnImmediate (timers.js:743:5)
Aug 15 08:11:06 raspberrypi homebridge[21855]: at processImmediate [as _immediateCallback] (timers.js:714:5)
Aug 15 08:11:06 raspberrypi homebridge[21855]: [2017-8-15 08:11:06] [Rauchmelder] Falling back to legacy API.
Aug 15 08:11:06 raspberrypi homebridge[21855]: [2017-8-15 08:11:06] [Rauchmelder] There was a problem authenticating with Nest.

```

**Comment by DJay79** [comment]
Same here. :/ 

```
Aug 15 12:28:48 raspberrypi homebridge[3157]: at NestProtectAccessory.NestDeviceAccessory.bindCharacteristic (/usr/local/lib/node_modules/homebridge-nest/lib/nest-device-accessory.js:65:9)
Aug 15 12:28:48 raspberrypi homebridge[3157]: at NestProtectAccessory.NestDeviceAccessory (/usr/local/lib/node_modules/homebridge-nest/lib/nest-device-accessory.js:52:10)
Aug 15 12:28:48 raspberrypi homebridge[3157]: at new NestProtectAccessory (/usr/local/lib/node_modules/homebridge-nest/lib/nest-protect-accessory.js:41:25)
Aug 15 12:28:48 raspberrypi homebridge[3157]: at NestPlatform.<anonymous> (/usr/local/lib/node_modules/homebridge-nest/index.js:117:23)
Aug 15 12:28:48 raspberrypi homebridge[3157]: at NestPlatform.<anonymous> (/usr/local/lib/node_modules/homebridge-nest/index.js:125:4)
Aug 15 12:28:48 raspberrypi homebridge[3157]: at /usr/local/lib/node_modules/homebridge-nest/index.js:152:28
Aug 15 12:28:48 raspberrypi homebridge[3157]: at <anonymous>
Aug 15 12:28:48 raspberrypi homebridge[3157]: [2017-8-15 12:28:48] Falling back to legacy API.
Aug 15 12:28:49 raspberrypi homebridge[3157]: /usr/local/lib/node_modules/homebridge-nest/node_modules/unofficial-nest-api/index.js:68
Aug 15 12:28:49 raspberrypi homebridge[3157]: nestSession.urls.transport_url = url.parse(nestSession.urls.transport_url);
Aug 15 12:28:49 raspberrypi homebridge[3157]: ^
Aug 15 12:28:49 raspberrypi homebridge[3157]: TypeError: Cannot read property 'transport_url' of undefined
Aug 15 12:28:49 raspberrypi homebridge[3157]: at done (/usr/local/lib/node_modules/homebridge-nest/node_modules/unofficial-nest-api/index.js:68:78)
Aug 15 12:28:49 raspberrypi homebridge[3157]: at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/homebridge-nest/node_modules/unofficial-nest-api/index.js:170:25)
Aug 15 12:28:49 raspberrypi homebridge[3157]: at emitNone (events.js:110:20)
Aug 15 12:28:49 raspberrypi homebridge[3157]: at IncomingMessage.emit (events.js:207:7)
Aug 15 12:28:49 raspberrypi homebridge[3157]: at endReadableNT (_stream_readable.js:1045:12)
Aug 15 12:28:49 raspberrypi homebridge[3157]: at _combinedTickCallback (internal/process/next_tick.js:138:11)
Aug 15 12:28:49 raspberrypi homebridge[3157]: at process._tickCallback (internal/process/next_tick.js:180:9)
Aug 15 12:28:49 raspberrypi systemd[1]: homebridge.service: main process exited, code=exited, status=1/FAILURE
Aug 15 12:28:49 raspberrypi systemd[1]: Unit homebridge.service entered failed state.
```

**Comment by pponce** [comment]
I also updated Homebridge to 0.4.23. and am getting this error when in start homebridge. Also homebridge restarts constantly. Not right away but is definitely not stable.

 TypeError: Cannot read property 'on' of undefined
    at NestThermostatAccessory.NestDeviceAccessory.bindCharacteristic (/home/pi/.nvm/versions/node/v6.10.2/lib/node_modules/homebridge-nest/lib/nest-device-accessory.js:65:9)
    at NestThermostatAccessory.NestDeviceAccessory (/home/pi/.nvm/versions/node/v6.10.2/lib/node_modules/homebridge-nest/lib/nest-device-accessory.js:52:10)
    at new NestThermostatAccessory (/home/pi/.nvm/versions/node/v6.10.2/lib/node_modules/homebridge-nest/lib/nest-thermostat-accessory.js:37:22)
    at Object.<anonymous> (/home/pi/.nvm/versions/node/v6.10.2/lib/node_modules/homebridge-nest/index.js:117:23)
    at Object.<anonymous> (/home/pi/.nvm/versions/node/v6.10.2/lib/node_modules/homebridge-nest/index.js:124:4)
    at /home/pi/.nvm/versions/node/v6.10.2/lib/node_modules/homebridge-nest/index.js:152:28

**Comment by DMBlakeley** [comment]
I had a similar problem with Homebridge 0.4.24 / hap-nodejs 0.4.29 and received the following error.  I have fallen back to Homebridge 0.4.22 / hap-nodes 0.4.27 and the issue was resolved.

[8/15/2017, 7:04:33 PM] TypeError: Cannot read property 'on' of undefined
    at NestThermostatAccessory.NestDeviceAccessory.bindCharacteristic (/usr/local/lib/node_modules/homebridge-nest/lib/nest-device-accessory.js:65:9)
    at NestThermostatAccessory.NestDeviceAccessory (/usr/local/lib/node_modules/homebridge-nest/lib/nest-device-accessory.js:52:10)
    at new NestThermostatAccessory (/usr/local/lib/node_modules/homebridge-nest/lib/nest-thermostat-accessory.js:35:22)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge-nest/index.js:117:23)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge-nest/index.js:124:4)
    at /usr/local/lib/node_modules/homebridge-nest/index.js:152:28
[8/15/2017, 7:04:33 PM] Falling back to legacy API.
[8/15/2017, 7:04:34 PM] Away for Nest is: false
[8/15/2017, 7:04:34 PM] Temperature unit for Nest is: Fahrenheit
[8/15/2017, 7:04:34 PM] Current temperature for Nest is: 26.92999
[8/15/2017, 7:04:34 PM] Current heating for Nest is: 2
[8/15/2017, 7:04:34 PM] Current humidity for Nest is: 61
[8/15/2017, 7:04:34 PM] Target heating for Nest is: 2
[8/15/2017, 7:04:34 PM] Target temperature for Nest is: 26.666666666666668
[8/15/2017, 7:04:34 PM] Initializing platform accessory 'Nest'...

**Comment by DJay79** [comment]
Updated to [homebridge@0.4.25](https://github.com/nfarina/homebridge) now it works again

**Comment by DMBlakeley** [comment]
Hi,

With 0.4.25 homebridge is again functional.  FYI, on startup I get 2 warnings:

HAP Warning: Characteristic 00000054-0000-1000-8000-0026BB765291 not in required or optional characteristics for service 0000003E-0000-1000-8000-0026BB765291. Adding anyway.
[8/16/2017, 12:51:34 PM] Software version for Living Room Thermostat (Nest) is: 5.6.3-1
...
HAP Warning: Characteristic 00000054-0000-1000-8000-0026BB765291 not in required or optional characteristics for service 0000003E-0000-1000-8000-0026BB765291. Adding anyway.
[8/16/2017, 12:51:34 PM] Software version for Living Room Nest Protect (Protect) is: 3.1.3rc2

I found out from Nick Farina/homebridge:

"That is expected. HomeKit no longer has Characteristic 54 (Software Version) as an optional characteristic for the the service 3E (Accessory Info). The plugin developer needs to resolve that, but everything should work fine unless Apple starts rejecting that characteristic. The warning is there to make sure people are aware in case they start having trouble. I'm going to try and determine a simple way to add the textual name, but for now the UUID will have to work.”

Regards,
Doug

---
Douglas Blakeley
douglas.blakeley@gmail.com
