### ISSUE TITLE
Reauthorizing error : TypeError: self.log.warn is not a function

### ISSUE THREAD

**Issue by davidhariri** [KraigM/homebridge-nest#161]
My HomeBridge to Nest API connection failed to authorize sometime yesterday and has been giving this error consistently ever since:

`Reauthorizing error : TypeError: self.log.warn is not a function`

I _think_ what's going on is there's a retry loop in [nest-connection.js](https://github.com/KraigM/homebridge-nest/blob/master/lib/nest-connection.js) that's failing because it's trying to log something using `self.log.warn` which doesn't exist in this context. I'm happy to patch this myself, but would like some input from @KraigM before I do.

This issue can be resolved with a restart of the container.

Thank you 😌

**Trace**:
```
2018-01-23 18:32:49,stdout,[2018-1-23 18:32:49] [Nest] [NestFirebase] Reauthorizing error : TypeError: self.log.warn is not a function
2018-01-23 18:32:44,stdout,at Timer.listOnTimeout (timers.js:270:5)[39m[22m
2018-01-23 18:32:44,stdout,at tryOnTimeout (timers.js:310:5)
2018-01-23 18:32:44,stdout,at ontimeout (timers.js:475:11)
2018-01-23 18:32:44,stdout,at Timeout._onTimeout (/homebridge/node_modules/bluebird/js/release/timers.js:26:46)
2018-01-23 18:32:44,stdout,at Promise._fulfill (/homebridge/node_modules/bluebird/js/release/promise.js:638:18)
2018-01-23 18:32:44,stdout,at Promise._settlePromises (/homebridge/node_modules/bluebird/js/release/promise.js:693:18)
2018-01-23 18:32:44,stdout,at Promise._settlePromise0 (/homebridge/node_modules/bluebird/js/release/promise.js:614:10)
2018-01-23 18:32:44,stdout,at Promise._settlePromise (/homebridge/node_modules/bluebird/js/release/promise.js:569:18)
2018-01-23 18:32:44,stdout,at Promise._settlePromiseFromHandler (/homebridge/node_modules/bluebird/js/release/promise.js:512:31)
2018-01-23 18:32:44,stdout,at tryCatcher (/homebridge/node_modules/bluebird/js/release/util.js:16:23)
2018-01-23 18:32:44,stdout,at /homebridge/node_modules/homebridge-nest/lib/nest-connection.js:73:14
```

This issue started as a result of this:

```
2018-01-22 16:28:30,stdout,"FIREBASE WARNING: auth() was canceled: {\"error\":\"service unavailable\",\"type\":\"https://developer.nest.com/documentation/cloud/error-messages#service-unavailable\",\"message\":\"service unavailable\",\"instance\":\"7090f2f2-f364-41fe-9dfd-cde41ed56d12\"} 
"
2018-01-22 15:39:07,stdout,[2018-1-22 15:39:07] [Nest] Temperature set to 20
2018-01-22 15:39:02,stdout,[2018-1-22 15:39:02] [Nest] Trying to set temperature 20
2018-01-22 14:37:02,stdout,[2018-1-22 14:37:02] [Nest] Temperature set to 20
```

**Comment by kcharwood** [comment]
I'm seeing this as well

**Comment by ghost** [comment]
Also having this issue

**Comment by justbcuz** [comment]
Also having the same issue. I just commented out the lines for now. But it is definitely a context scope issue.

**Comment by chrisjshull** [comment]
Great news! I have taken up maintenance of the homebridge-nest plugin in npm. The source code now lives at https://github.com/chrisjshull/homebridge-nest/. To update to the latest version of homebridge-nest, simply run `npm update -g homebridge-nest`.

I think this issue is fixed there, but if not please file this issue against that repo. Thanks!

**Comment by davidhariri** [comment]
Great! Will do.
