### ISSUE TITLE
Error: The requested accessory 'Nest' was not registered by any plugin.

### ISSUE THREAD

**Issue by jsdorais** [KraigM/homebridge-nest#175]
I've installed homebridge and homebridge-nest with success on my Raspberry Pi 3 (running Raspian).

After copying the config.json file into the appropriate directory and running the homebridge command, I get the following error:

> pi@raspberrypi:~ $ homebridge * WARNING The program 'node' uses the Apple Bonjour compatibility layer of Avahi. WARNING Please fix your application to use the native API of Avahi! WARNING For more information see http://0pointer.de/avahi-compat?s=libdns_sd&e=node WARNING The program 'node' called 'DNSServiceRegister()' which is not supported (or only supported partially) in the Apple Bonjour compatibility layer of Avahi. WARNING Please fix your application to use the native API of Avahi! WARNING * For more information see http://0pointer.de/avahi-compat?s=libdns_sd&e=node&f=DNSServiceRegister [2018-3-4 14:29:38] Loaded plugin: homebridge-nest [2018-3-4 14:29:38] Registering platform 'homebridge-nest.Nest' [2018-3-4 14:29:38] --- [2018-3-4 14:29:38] Loaded config.json with 1 accessories and 1 platforms. [2018-3-4 14:29:38] --- [2018-3-4 14:29:38] Loading 1 platforms... [2018-3-4 14:29:38] [Nest] Initializing Nest platform... [2018-3-4 14:29:38] [Nest] Fetching Nest devices. [2018-3-4 14:29:38] Loading 1 accessories... /usr/lib/node_modules/homebridge/lib/api.js:64 throw new Error("The requested accessory '" + name + "' was not registered by any plugin."); ^
> 
> Error: The requested accessory 'Nest' was not registered by any plugin. at API.accessory (/usr/lib/node_modules/homebridge/lib/api.js:64:13) at Server._loadAccessories (/usr/lib/node_modules/homebridge/lib/server.js:264:42) at Server.run (/usr/lib/node_modules/homebridge/lib/server.js:86:38) at module.exports (/usr/lib/node_modules/homebridge/lib/cli.js:40:10) at Object. (/usr/lib/node_modules/homebridge/bin/homebridge:17:22) at Module._compile (module.js:643:30) at Object.Module._extensions..js (module.js:654:10) at Module.load (module.js:556:32) at tryModuleLoad (module.js:499:12) at Function.Module._load (module.js:491:3) at Function.Module.runMain (module.js:684:10) at startup (bootstrap_node.js:187:16) at bootstrap_node.js:608:3 pi@raspberrypi:~ $

My config.json file looks like this:

```
 {
    "bridge": {
        "name": "Homebridge",
        "username": "CC:22:3D:E3:CE:30",
        "port": 51826,
        "pin": "031-45-154"
    },

"description": "This is an example configuration file with one fake accessory and one fake platform. You can use this as a template for creating your own configuration file containing devices you actually own.",

"accessories": [{
    "accessory": "Nest",
    "name": "Nest"
}],

"platforms": [{
    "platform": "Nest",


    "clientId": "ID from Nest Dev",
    "clientSecret": "secret code from Nest Dev",
    "code": "code generated from Nest Dev"
}]
}
```

Banging my head! Any pointers would be appreciated.

**Comment by chrisjshull** [comment]
Great news! I have taken up maintenance of the homebridge-nest plugin in npm. The source code now lives at https://github.com/chrisjshull/homebridge-nest/. Please file future issues against that repo. Thanks!

For this one though, try deleting the accessories section: `"accessories": []`. I' pretty sure the platforms section is all that you need.

**Comment by jsdorais** [comment]
Chris,

Your suggestion worked!  Thank you and congrats on maintaining the plugin…much appreciated.

Enjoy the rest of the week.
___________________
Jean-Sébastien Dorais
917.302.8426
