### ISSUE TITLE
Thermostat is not online message?

### ISSUE THREAD

**Issue by dazza120** [KraigM/homebridge-nest#180]
Hi guys i've had this running on a vm for a while i have updated and its been great now until i switched it to an unraid docker now i get this can someone help please

at TLSSocket.ondata (_stream_readable.js:646:20)
at TLSSocket.emit (events.js:160:13)
at addChunk (_stream_readable.js:269:12)
at readableAddChunk (_stream_readable.js:256:11) code: 'THERMOSTAT IS NOT ONLINE' },
isOperational: true,
code: 'THERMOSTAT IS NOT ONLINE' }
[2018-4-16 14:46:40] [Nest] Queuing to set temperature 24
FIREBASE WARNING: set at /devices/thermostats/fJbEVt9K1YVHh7kuAaodxUVMq-rZ5nt6/target_temperature_c failed: Thermostat is not online

[2018-4-16 14:46:45] [Nest] Temperature set to 24 { Error: THERMOSTAT IS NOT ONLINE: {"error":"Thermostat is not online","type":"https://developer.nest.com/documentation/cloud/error-messages#not-online","message":"Thermostat is not online","instance":"16b7d862-8ab8-4d70-b591-712605753e2f"}

at /usr/local/lib/node_modules/homebridge-nest/node_modules/firebase/lib/firebase-node.js:226:115
at ec (/usr/local/lib/node_modules/homebridge-nest/node_modules/firebase/lib/firebase-node.js:52:165)
at Pi (/usr/local/lib/node_modules/homebridge-nest/node_modules/firebase/lib/firebase-node.js:226:23)
at /usr/local/lib/node_modules/homebridge-nest/node_modules/firebase/lib/firebase-node.js:221:404
at /usr/local/lib/node_modules/homebridge-nest/node_modules/firebase/lib/firebase-node.js:184:355
at Rh.h.Jd (/usr/local/lib/node_modules/homebridge-nest/node_modules/firebase/lib/firebase-node.js:186:104)
at Fh.Jd (/usr/local/lib/node_modules/homebridge-nest/node_modules/firebase/lib/firebase-node.js:176:364)
at wh.Jg (/usr/local/lib/node_modules/homebridge-nest/node_modules/firebase/lib/firebase-node.js:174:280)
at zh (/usr/local/lib/node_modules/homebridge-nest/node_modules/firebase/lib/firebase-node.js:168:464)
at Client.Ka.onmessage (/usr/local/lib/node_modules/homebridge-nest/node_modules/firebase/lib/firebase-node.js:167:321)
at Client.dispatchEvent (/usr/local/lib/node_modules/homebridge-nest/node_modules/firebase/node_modules/faye-websocket/lib/faye/websocket/api/event_target.js:22:30)
at Client._receiveMessage (/usr/local/lib/node_modules/homebridge-nest/node_modules/firebase/node_modules/faye-websocket/lib/faye/websocket/api.js:134:10)
at Client.<anonymous> (/usr/local/lib/node_modules/homebridge-nest/node_modules/firebase/node_modules/faye-websocket/lib/faye/websocket/api.js:34:49)
at Client.emit (events.js:165:20)
at Client.<anonymous> (/usr/local/lib/node_modules/homebridge-nest/node_modules/firebase/node_modules/faye-websocket/node_modules/websocket-driver/lib/websocket/driver/hybi.js:451:14)

at pipe (/usr/local/lib/node_modules/homebridge-nest/node_modules/firebase/node_modules/faye-websocket/node_modules/websocket-driver/node_modules/websocket-extensions/lib/pipeline/index.js:37:40)

at Pipeline._loop (/usr/local/lib/node_modules/homebridge-nest/node_modules/firebase/node_modules/faye-websocket/node_modules/websocket-driver/node_modules/websocket-extensions/lib/pipeline/index.js:44:3)

at Pipeline.processIncomingMessage (/usr/local/lib/node_modules/homebridge-nest/node_modules/firebase/node_modules/faye-websocket/node_modules/websocket-driver/node_modules/websocket-extensions/lib/pipeline/index.js:13:8)

at Extensions.processIncomingMessage (/usr/local/lib/node_modules/homebridge-nest/node_modules/firebase/node_modules/faye-websocket/node_modules/websocket-driver/node_modules/websocket-extensions/lib/websocket_extensions.js:133:20)

at Client._emitMessage (/usr/local/lib/node_modules/homebridge-nest/node_modules/firebase/node_modules/faye-websocket/node_modules/websocket-driver/lib/websocket/driver/hybi.js:442:22)

at Client._emitFrame (/usr/local/lib/node_modules/homebridge-nest/node_modules/firebase/node_modules/faye-websocket/node_modules/websocket-driver/lib/websocket/driver/hybi.js:405:19)

at Client.parse (/usr/local/lib/node_modules/homebridge-nest/node_modules/firebase/node_modules/faye-websocket/node_modules/websocket-driver/lib/websocket/driver/hybi.js:144:18)

at Client.parse (/usr/local/lib/node_modules/homebridge-nest/node_modules/firebase/node_modules/faye-websocket/node_modules/websocket-driver/lib/websocket/driver/client.js:56:58)

at IO.write (/usr/local/lib/node_modules/homebridge-nest/node_modules/firebase/node_modules/faye-websocket/node_modules/websocket-driver/lib/websocket/streams.js:80:16)

at TLSSocket.ondata (_stream_readable.js:646:20)
at TLSSocket.emit (events.js:160:13)
at addChunk (_stream_readable.js:269:12)
at readableAddChunk (_stream_readable.js:256:11)
cause: { Error: THERMOSTAT IS NOT ONLINE: {"error":"Thermostat is not online","type":"https://developer.nest.com/documentation/cloud/error-messages#not-online","message":"Thermostat is not online","instance":"16b7d862-8ab8-4d70-b591-712605753e2f"}

at /usr/local/lib/node_modules/homebridge-nest/node_modules/firebase/lib/firebase-node.js:226:115
at ec (/usr/local/lib/node_modules/homebridge-nest/node_modules/firebase/lib/firebase-node.js:52:165)
at Pi (/usr/local/lib/node_modules/homebridge-nest/node_modules/firebase/lib/firebase-node.js:226:23)
at /usr/local/lib/node_modules/homebridge-nest/node_modules/firebase/lib/firebase-node.js:221:404
at /usr/local/lib/node_modules/homebridge-nest/node_modules/firebase/lib/firebase-node.js:184:355
at Rh.h.Jd (/usr/local/lib/node_modules/homebridge-nest/node_modules/firebase/lib/firebase-node.js:186:104)
at Fh.Jd (/usr/local/lib/node_modules/homebridge-nest/node_modules/firebase/lib/firebase-node.js:176:364)
at wh.Jg (/usr/local/lib/node_modules/homebridge-nest/node_modules/firebase/lib/firebase-node.js:174:280)
at zh (/usr/local/lib/node_modules/homebridge-nest/node_modules/firebase/lib/firebase-node.js:168:464)
at Client.Ka.onmessage (/usr/local/lib/node_modules/homebridge-nest/node_modules/firebase/lib/firebase-node.js:167:321)
at Client.dispatchEvent (/usr/local/lib/node_modules/homebridge-nest/node_modules/firebase/node_modules/faye-websocket/lib/faye/websocket/api/event_target.js:22:30)
at Client._receiveMessage (/usr/local/lib/node_modules/homebridge-nest/node_modules/firebase/node_modules/faye-websocket/lib/faye/websocket/api.js:134:10)
at Client.<anonymous> (/usr/local/lib/node_modules/homebridge-nest/node_modules/firebase/node_modules/faye-websocket/lib/faye/websocket/api.js:34:49)
at Client.emit (events.js:165:20)
at Client.<anonymous> (/usr/local/lib/node_modules/homebridge-nest/node_modules/firebase/node_modules/faye-websocket/node_modules/websocket-driver/lib/websocket/driver/hybi.js:451:14)

at pipe (/usr/local/lib/node_modules/homebridge-nest/node_modules/firebase/node_modules/faye-websocket/node_modules/websocket-driver/node_modules/websocket-extensions/lib/pipeline/index.js:37:40)

at Pipeline._loop (/usr/local/lib/node_modules/homebridge-nest/node_modules/firebase/node_modules/faye-websocket/node_modules/websocket-driver/node_modules/websocket-extensions/lib/pipeline/index.js:44:3)

at Pipeline.processIncomingMessage (/usr/local/lib/node_modules/homebridge-nest/node_modules/firebase/node_modules/faye-websocket/node_modules/websocket-driver/node_modules/websocket-extensions/lib/pipeline/index.js:13:8)

at Extensions.processIncomingMessage (/usr/local/lib/node_modules/homebridge-nest/node_modules/firebase/node_modules/faye-websocket/node_modules/websocket-driver/node_modules/websocket-extensions/lib/websocket_extensions.js:133:20)

at Client._emitMessage (/usr/local/lib/node_modules/homebridge-nest/node_modules/firebase/node_modules/faye-websocket/node_modules/websocket-driver/lib/websocket/driver/hybi.js:442:22)

at Client._emitFrame (/usr/local/lib/node_modules/homebridge-nest/node_modules/firebase/node_modules/faye-websocket/node_modules/websocket-driver/lib/websocket/driver/hybi.js:405:19)

at Client.parse (/usr/local/lib/node_modules/homebridge-nest/node_modules/firebase/node_modules/faye-websocket/node_modules/websocket-driver/lib/websocket/driver/hybi.js:144:18)

at Client.parse (/usr/local/lib/node_modules/homebridge-nest/node_modules/firebase/node_modules/faye-websocket/node_modules/websocket-driver/lib/websocket/driver/client.js:56:58)

at IO.write (/usr/local/lib/node_modules/homebridge-nest/node_modules/firebase/node_modules/faye-websocket/node_modules/websocket-driver/lib/websocket/streams.js:80:16)

at TLSSocket.ondata (_stream_readable.js:646:20)
at TLSSocket.emit (events.js:160:13)
at addChunk (_stream_readable.js:269:12)
at readableAddChunk (_stream_readable.js:256:11) code: 'THERMOSTAT IS NOT ONLINE' },
isOperational: true,
code: 'THERMOSTAT IS NOT ONLINE' }

**Comment by dazza120** [comment]
It was blocked by pi-hole not sure how it was working on the OSX vm but it is sorted. It was all my fault apologies :)
