### ISSUE TITLE
Auth failed

### ISSUE THREAD

**Issue by Bullet55NL** [KraigM/homebridge-nest#193]
Please help... i get this error;

Auth failed which likely means the code is no longer valid. Should be able to generate a new one at https://home.nest.com/logxxx-xxx-xxx-xxx-xxx

[8/8/2018, 7:40:48 AM] [Nest] { RequestError: Error: getaddrinfo EAI_AGAIN api.home.nest.com api.home.nest.com:443
    at new RequestError (/home/pi/.nvm/versions/node/v10.4.0/lib/node_modules/homebridge-nest/node_modules/request-promise/lib/errors.js:11:15)
    at Request.RP$callback [as _callback] (/home/pi/.nvm/versions/node/v10.4.0/lib/node_modules/homebridge-nest/node_modules/request-promise/lib/rp.js:60:32)
    at self.callback (/home/pi/.nvm/versions/node/v10.4.0/lib/node_modules/homebridge-nest/node_modules/request/request.js:185:22)
    at Request.emit (events.js:182:13)
    at Request.onRequestError (/home/pi/.nvm/versions/node/v10.4.0/lib/node_modules/homebridge-nest/node_modules/request/request.js:877:8)
    at ClientRequest.emit (events.js:182:13)
    at TLSSocket.socketErrorListener (_http_client.js:382:9)
    at TLSSocket.emit (events.js:182:13)
    at emitErrorNT (internal/streams/destroy.js:82:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)
    at process._tickCallback (internal/process/next_tick.js:63:19)
  name: 'RequestError',
  message:
   'Error: getaddrinfo EAI_AGAIN api.home.nest.com api.home.nest.com:443',
  cause:
   { Error: getaddrinfo EAI_AGAIN api.home.nest.com api.home.nest.com:443
       at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:50:26)
     errno: 'EAI_AGAIN',
     code: 'EAI_AGAIN',
     syscall: 'getaddrinfo',
     hostname: 'api.home.nest.com',
     host: 'api.home.nest.com',
     port: 443 },
  error:
   { Error: getaddrinfo EAI_AGAIN api.home.nest.com api.home.nest.com:443
       at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:50:26)
     errno: 'EAI_AGAIN',
     code: 'EAI_AGAIN',
     syscall: 'getaddrinfo',
     hostname: 'api.home.nest.com',
     host: 'api.home.nest.com',
     port: 443 },
  options:
   { method: 'POST',
     uri: 'https://api.home.nest.com/oauth2/access_token',
     form:
      { client_id: 'xxx-xxx-xxx',
        client_secret: 'xx-xxxx-xxx-xxx',
        code: 'xxx-xxx-xxx-xxx',
        grant_type: 'authorization_code' },
     callback: undefined,
     transform: undefined,
     simple: true,
     resolveWithFullResponse: false },
  response: undefined }
Setup Payload:
X-HM://0023JDH7T9H6M

**### Json.config;**

{
    "bridge": {
        "name": "HomeBridgeOtter5",
        "username": "CC:22:3D:E3:CE:93",
        "port": 51826,
        "pin": "041-01-993"
 },
 	"platforms": [
                {
 			"platform": "Nest",
 			"token": "",
 			"clientId": "xxx-xxx-xxx",
 			"clientSecret": "xxx-xxx-xxx",
 			"code": "xxx-xxx-xxx"

      }

    ]
}

**Comment by Bullet55NL** [comment]
I figured it out. It had something to do with my network. I noticed this because i also wasn't able to do; ''sudo apt-get update'' I rebooted my router and poof. Everything worked again :-)
