### ISSUE TITLE
Can't find Token in the log file - Says ERROR Service Unavailable

### ISSUE THREAD

**Issue by Azzhoe** [KraigM/homebridge-nest#198]
when looking through the log file, it seems it can't access something and gives me an ERROR Service Unavailable.

**Comment by fergbrain** [comment]
Here's the error I get (with redacted instance id):

```
[Nest] { Error: SERVICE UNAVAILABLE: {"error":"service unavailable","type":"https://developer.nest.com/documentation/cloud/error-messages#service-unavailable","message":"service unavailable","instance":"aaaaaaaa-bbbb-cccc-dddd-eeeeeeeeeeee"}
    at Yg (/usr/local/lib/node_modules/homebridge-nest/node_modules/firebase/lib/firebase-node.js:150:468)
    at Object.Cc (/usr/local/lib/node_modules/homebridge-nest/node_modules/firebase/lib/firebase-node.js:149:255)
    at /usr/local/lib/node_modules/homebridge-nest/node_modules/firebase/lib/firebase-node.js:182:177
    at Rh.h.Jd (/usr/local/lib/node_modules/homebridge-nest/node_modules/firebase/lib/firebase-node.js:186:104)
    at Fh.Jd (/usr/local/lib/node_modules/homebridge-nest/node_modules/firebase/lib/firebase-node.js:176:364)
    at wh.Jg (/usr/local/lib/node_modules/homebridge-nest/node_modules/firebase/lib/firebase-node.js:174:280)
    at zh (/usr/local/lib/node_modules/homebridge-nest/node_modules/firebase/lib/firebase-node.js:168:464)
    at Client.Ka.onmessage (/usr/local/lib/node_modules/homebridge-nest/node_modules/firebase/lib/firebase-node.js:167:321)
    at Client.dispatchEvent (/usr/local/lib/node_modules/homebridge-nest/node_modules/firebase/node_modules/faye-websocket/lib/faye/websocket/api/event_target.js:22:30)
    at Client._receiveMessage (/usr/local/lib/node_modules/homebridge-nest/node_modules/firebase/node_modules/faye-websocket/lib/faye/websocket/api.js:134:10)
    at Client.<anonymous> (/usr/local/lib/node_modules/homebridge-nest/node_modules/firebase/node_modules/faye-websocket/lib/faye/websocket/api.js:34:49)
    at Client.emit (events.js:187:15)
    at Client.<anonymous> (/usr/local/lib/node_modules/homebridge-nest/node_modules/firebase/node_modules/faye-websocket/node_modules/websocket-driver/lib/websocket/driver/hybi.js:451:14)
    at pipe (/usr/local/lib/node_modules/homebridge-nest/node_modules/firebase/node_modules/faye-websocket/node_modules/websocket-driver/node_modules/websocket-extensions/lib/pipeline/index.js:37:40)
    at Pipeline._loop (/usr/local/lib/node_modules/homebridge-nest/node_modules/firebase/node_modules/faye-websocket/node_modules/websocket-driver/node_modules/websocket-extensions/lib/pipeline/index.js:44:3)
    at Pipeline.processIncomingMessage (/usr/local/lib/node_modules/homebridge-nest/node_modules/firebase/node_modules/faye-websocket/node_modules/websocket-driver/node_modules/websocket-extensions/lib/pipeline/index.js:13:8)
    at Extensions.processIncomingMessage (/usr/local/lib/node_modules/homebridge-nest/node_modules/firebase/node_modules/faye-websocket/node_modules/websocket-driver/node_modules/websocket-extensions/lib/websocket_extensions.js:133:20)
    at Client._emitMessage (/usr/local/lib/node_modules/homebridge-nest/node_modules/firebase/node_modules/faye-websocket/node_modules/websocket-driver/lib/websocket/driver/hybi.js:442:22)
    at Client._emitFrame (/usr/local/lib/node_modules/homebridge-nest/node_modules/firebase/node_modules/faye-websocket/node_modules/websocket-driver/lib/websocket/driver/hybi.js:405:19)
    at Client.parse (/usr/local/lib/node_modules/homebridge-nest/node_modules/firebase/node_modules/faye-websocket/node_modules/websocket-driver/lib/websocket/driver/hybi.js:144:18)
    at Client.parse (/usr/local/lib/node_modules/homebridge-nest/node_modules/firebase/node_modules/faye-websocket/node_modules/websocket-driver/lib/websocket/driver/client.js:56:58)
    at IO.write (/usr/local/lib/node_modules/homebridge-nest/node_modules/firebase/node_modules/faye-websocket/node_modules/websocket-driver/lib/websocket/streams.js:80:16)
  cause:
   { Error: SERVICE UNAVAILABLE: {"error":"service unavailable","type":"https://developer.nest.com/documentation/cloud/error-messages#service-unavailable","message":"service unavailable","instance":"aaaaaaaa-bbbb-cccc-dddd-eeeeeeeeeeee"}
       at Yg (/usr/local/lib/node_modules/homebridge-nest/node_modules/firebase/lib/firebase-node.js:150:468)
       at Object.Cc (/usr/local/lib/node_modules/homebridge-nest/node_modules/firebase/lib/firebase-node.js:149:255)
       at /usr/local/lib/node_modules/homebridge-nest/node_modules/firebase/lib/firebase-node.js:182:177
       at Rh.h.Jd (/usr/local/lib/node_modules/homebridge-nest/node_modules/firebase/lib/firebase-node.js:186:104)
       at Fh.Jd (/usr/local/lib/node_modules/homebridge-nest/node_modules/firebase/lib/firebase-node.js:176:364)
       at wh.Jg (/usr/local/lib/node_modules/homebridge-nest/node_modules/firebase/lib/firebase-node.js:174:280)
       at zh (/usr/local/lib/node_modules/homebridge-nest/node_modules/firebase/lib/firebase-node.js:168:464)
       at Client.Ka.onmessage (/usr/local/lib/node_modules/homebridge-nest/node_modules/firebase/lib/firebase-node.js:167:321)
       at Client.dispatchEvent (/usr/local/lib/node_modules/homebridge-nest/node_modules/firebase/node_modules/faye-websocket/lib/faye/websocket/api/event_target.js:22:30)
       at Client._receiveMessage (/usr/local/lib/node_modules/homebridge-nest/node_modules/firebase/node_modules/faye-websocket/lib/faye/websocket/api.js:134:10)
       at Client.<anonymous> (/usr/local/lib/node_modules/homebridge-nest/node_modules/firebase/node_modules/faye-websocket/lib/faye/websocket/api.js:34:49)
       at Client.emit (events.js:187:15)
       at Client.<anonymous> (/usr/local/lib/node_modules/homebridge-nest/node_modules/firebase/node_modules/faye-websocket/node_modules/websocket-driver/lib/websocket/driver/hybi.js:451:14)
       at pipe (/usr/local/lib/node_modules/homebridge-nest/node_modules/firebase/node_modules/faye-websocket/node_modules/websocket-driver/node_modules/websocket-extensions/lib/pipeline/index.js:37:40)
       at Pipeline._loop (/usr/local/lib/node_modules/homebridge-nest/node_modules/firebase/node_modules/faye-websocket/node_modules/websocket-driver/node_modules/websocket-extensions/lib/pipeline/index.js:44:3)
       at Pipeline.processIncomingMessage (/usr/local/lib/node_modules/homebridge-nest/node_modules/firebase/node_modules/faye-websocket/node_modules/websocket-driver/node_modules/websocket-extensions/lib/pipeline/index.js:13:8)
       at Extensions.processIncomingMessage (/usr/local/lib/node_modules/homebridge-nest/node_modules/firebase/node_modules/faye-websocket/node_modules/websocket-driver/node_modules/websocket-extensions/lib/websocket_extensions.js:133:20)
       at Client._emitMessage (/usr/local/lib/node_modules/homebridge-nest/node_modules/firebase/node_modules/faye-websocket/node_modules/websocket-driver/lib/websocket/driver/hybi.js:442:22)
       at Client._emitFrame (/usr/local/lib/node_modules/homebridge-nest/node_modules/firebase/node_modules/faye-websocket/node_modules/websocket-driver/lib/websocket/driver/hybi.js:405:19)
       at Client.parse (/usr/local/lib/node_modules/homebridge-nest/node_modules/firebase/node_modules/faye-websocket/node_modules/websocket-driver/lib/websocket/driver/hybi.js:144:18)
       at Client.parse (/usr/local/lib/node_modules/homebridge-nest/node_modules/firebase/node_modules/faye-websocket/node_modules/websocket-driver/lib/websocket/driver/client.js:56:58)
       at IO.write (/usr/local/lib/node_modules/homebridge-nest/node_modules/firebase/node_modules/faye-websocket/node_modules/websocket-driver/lib/websocket/streams.js:80:16) code: 'SERVICE UNAVAILABLE' },
  isOperational: true,
  code: 'SERVICE UNAVAILABLE' }
```

**Comment by seanvk** [comment]
I'm getting the same error when trying to add my Nest to the home bridge.

**Comment by dpyy** [comment]
Same what is the fix??
