### ISSUE TITLE
first setup, don't get token at first launch

### ISSUE THREAD

**Issue by rhapsfx** [KraigM/homebridge-nest#60]
I have configured  the config file according to guideline, but at first launch I never the the token code.
It only show that I am not authorize and it fails back to legacy API
What wonder I what I have wrong and if I can get the token to be added to the config file.

Thanks

> [6/14/2016, 6:01:38 PM] Loaded plugin: homebridge-nest
[6/14/2016, 6:01:38 PM] Registering platform 'homebridge-nest.Nest'
[6/14/2016, 6:01:38 PM] ---
[6/14/2016, 6:01:38 PM] Loaded config.json with 0 accessories and 1 platforms.
[6/14/2016, 6:01:38 PM] ---
[6/14/2016, 6:01:38 PM] Loading 1 platforms...
[6/14/2016, 6:01:38 PM] Initializing Nest platform...
[6/14/2016, 6:01:38 PM] Fetching Nest devices.
[6/14/2016, 6:01:39 PM] { Error: UNAUTHORIZED: {"error":"unauthorized","type":"https://developer.nest.com/documentation/cloud/error-messages#auth-error","message":"unauthorized","instance":"ee2e6fab-3e97-4b10-8384-f0062ed1f4c7"}
    at Error (native)
    at Yg (/usr/local/lib/node_modules/homebridge-nest/node_modules/firebase/lib/firebase-node.js:150:468)
    at Object.Cc (/usr/local/lib/node_modules/homebridge-nest/node_modules/firebase/lib/firebase-node.js:149:255)
    at /usr/local/lib/node_modules/homebridge-nest/node_modules/firebase/lib/firebase-node.js:182:177
    at Rh.h.Jd (/usr/local/lib/node_modules/homebridge-nest/node_modules/firebase/lib/firebase-node.js:186:104)
    at Fh.Jd (/usr/local/lib/node_modules/homebridge-nest/node_modules/firebase/lib/firebase-node.js:176:364)
    at wh.Jg (/usr/local/lib/node_modules/homebridge-nest/node_modules/firebase/lib/firebase-node.js:174:280)
    at zh (/usr/local/lib/node_modules/homebridge-nest/node_modules/firebase/lib/firebase-node.js:168:464)
    at Ka.onmessage (/usr/local/lib/node_modules/homebridge-nest/node_modules/firebase/lib/firebase-node.js:167:321)
    at EventTarget.dispatchEvent (/usr/local/lib/node_modules/homebridge-nest/node_modules/firebase/node_modules/faye-websocket/lib/faye/websocket/api/event_target.js:22:30)
    at instance._receiveMessage (/usr/local/lib/node_modules/homebridge-nest/node_modules/firebase/node_modules/faye-websocket/lib/faye/websocket/api.js:134:10)
    at .<anonymous> (/usr/local/lib/node_modules/homebridge-nest/node_modules/firebase/node_modules/faye-websocket/lib/faye/websocket/api.js:34:49)
    at emitOne (events.js:101:20)
    at emit (events.js:188:7)
    at .<anonymous> (/usr/local/lib/node_modules/homebridge-nest/node_modules/firebase/node_modules/faye-websocket/node_modules/websocket-driver/lib/websocket/driver/hybi.js:451:14)
    at pipe (/usr/local/lib/node_modules/homebridge-nest/node_modules/firebase/node_modules/faye-websocket/node_modules/websocket-driver/node_modules/websocket-extensions/lib/pipeline/index.js:37:40)
    at Pipeline._loop (/usr/local/lib/node_modules/homebridge-nest/node_modules/firebase/node_modules/faye-websocket/node_modules/websocket-driver/node_modules/websocket-extensions/lib/pipeline/index.js:44:3)
    at Pipeline.processIncomingMessage (/usr/local/lib/node_modules/homebridge-nest/node_modules/firebase/node_modules/faye-websocket/node_modules/websocket-driver/node_modules/websocket-extensions/lib/pipeline/index.js:13:8)
    at instance.processIncomingMessage (/usr/local/lib/node_modules/homebridge-nest/node_modules/firebase/node_modules/faye-websocket/node_modules/websocket-driver/node_modules/websocket-extensions/lib/websocket_extensions.js:133:20)
    at instance._emitMessage (/usr/local/lib/node_modules/homebridge-nest/node_modules/firebase/node_modules/faye-websocket/node_modules/websocket-driver/lib/websocket/driver/hybi.js:442:22)
    at instance._emitFrame (/usr/local/lib/node_modules/homebridge-nest/node_modules/firebase/node_modules/faye-websocket/node_modules/websocket-driver/lib/websocket/driver/hybi.js:405:19)
    at instance.parse (/usr/local/lib/node_modules/homebridge-nest/node_modules/firebase/node_modules/faye-websocket/node_modules/websocket-driver/lib/websocket/driver/hybi.js:144:18)
  cause: 
   { Error: UNAUTHORIZED: {"error":"unauthorized","type":"https://developer.nest.com/documentation/cloud/error-messages#auth-error","message":"unauthorized","instance":"ee2e6fab-3e97-4b10-8384-f0062ed1f4c7"}
       at Error (native)
       at Yg (/usr/local/lib/node_modules/homebridge-nest/node_modules/firebase/lib/firebase-node.js:150:468)
       at Object.Cc (/usr/local/lib/node_modules/homebridge-nest/node_modules/firebase/lib/firebase-node.js:149:255)
       at /usr/local/lib/node_modules/homebridge-nest/node_modules/firebase/lib/firebase-node.js:182:177
       at Rh.h.Jd (/usr/local/lib/node_modules/homebridge-nest/node_modules/firebase/lib/firebase-node.js:186:104)
       at Fh.Jd (/usr/local/lib/node_modules/homebridge-nest/node_modules/firebase/lib/firebase-node.js:176:364)
       at wh.Jg (/usr/local/lib/node_modules/homebridge-nest/node_modules/firebase/lib/firebase-node.js:174:280)
       at zh (/usr/local/lib/node_modules/homebridge-nest/node_modules/firebase/lib/firebase-node.js:168:464)
       at Ka.onmessage (/usr/local/lib/node_modules/homebridge-nest/node_modules/firebase/lib/firebase-node.js:167:321)
       at EventTarget.dispatchEvent (/usr/local/lib/node_modules/homebridge-nest/node_modules/firebase/node_modules/faye-websocket/lib/faye/websocket/api/event_target.js:22:30)
       at instance._receiveMessage (/usr/local/lib/node_modules/homebridge-nest/node_modules/firebase/node_modules/faye-websocket/lib/faye/websocket/api.js:134:10)
       at .<anonymous> (/usr/local/lib/node_modules/homebridge-nest/node_modules/firebase/node_modules/faye-websocket/lib/faye/websocket/api.js:34:49)
       at emitOne (events.js:101:20)
       at emit (events.js:188:7)
       at .<anonymous> (/usr/local/lib/node_modules/homebridge-nest/node_modules/firebase/node_modules/faye-websocket/node_modules/websocket-driver/lib/websocket/driver/hybi.js:451:14)
       at pipe (/usr/local/lib/node_modules/homebridge-nest/node_modules/firebase/node_modules/faye-websocket/node_modules/websocket-driver/node_modules/websocket-extensions/lib/pipeline/index.js:37:40)
       at Pipeline._loop (/usr/local/lib/node_modules/homebridge-nest/node_modules/firebase/node_modules/faye-websocket/node_modules/websocket-driver/node_modules/websocket-extensions/lib/pipeline/index.js:44:3)
       at Pipeline.processIncomingMessage (/usr/local/lib/node_modules/homebridge-nest/node_modules/firebase/node_modules/faye-websocket/node_modules/websocket-driver/node_modules/websocket-extensions/lib/pipeline/index.js:13:8)
       at instance.processIncomingMessage (/usr/local/lib/node_modules/homebridge-nest/node_modules/firebase/node_modules/faye-websocket/node_modules/websocket-driver/node_modules/websocket-extensions/lib/websocket_extensions.js:133:20)
       at instance._emitMessage (/usr/local/lib/node_modules/homebridge-nest/node_modules/firebase/node_modules/faye-websocket/node_modules/websocket-driver/lib/websocket/driver/hybi.js:442:22)
       at instance._emitFrame (/usr/local/lib/node_modules/homebridge-nest/node_modules/firebase/node_modules/faye-websocket/node_modules/websocket-driver/lib/websocket/driver/hybi.js:405:19)
       at instance.parse (/usr/local/lib/node_modules/homebridge-nest/node_modules/firebase/node_modules/faye-websocket/node_modules/websocket-driver/lib/websocket/driver/hybi.js:144:18) code: 'UNAUTHORIZED' },
  isOperational: true,
  code: 'UNAUTHORIZED' }
[6/14/2016, 6:01:39 PM] Falling back to legacy API.
[6/14/2016, 6:01:41 PM] Away for Nest09AA01AC46150D9W is: true
[6/14/2016, 6:01:41 PM] Temperature unit for Nest09AA01AC46150D9W is: Celsius
[6/14/2016, 6:01:41 PM] Current temperature for Nest09AA01AC46150D9W is: 22
[6/14/2016, 6:01:41 PM] Current heating for Nest09AA01AC46150D9W is: 0
[6/14/2016, 6:01:41 PM] Current humidity for Nest09AA01AC46150D9W is: 65
[6/14/2016, 6:01:41 PM] Target heating for Nest09AA01AC46150D9W is: 1
[6/14/2016, 6:01:41 PM] Target temperature for Nest09AA01AC46150D9W is: 20.466
[6/14/2016, 6:01:41 PM] Initializing platform accessory 'Nest09AA01AC46150D9W'...
Scan this code with your HomeKit App on your iOS device to pair with Homebridge:
                       
    ┌────────────┐     
    │xxx-xx-xxx │     
    └────────────┘     
                       
[6/14/2016, 6:01:41 PM] Homebridge is running on port 51826.

**Comment by KraigM** [comment]
Did you follow the guide on how to setup the dev account and what not?

**Comment by rhapsfx** [comment]
Yea I did. I got a product set with API. Get all information about API access except the token. Only a URL Token.

**Comment by KraigM** [comment]
You did the part where you get the pin code from the website and add it to the config with "clientId" and "clientSecret", run it once, and obtain the token from the command line?

Keep in mind that the pin code only works once.  If you restart homebridge the pin code will fail to authorize.  Also, when using the pin code, you cannot have a token configured at all, otherwise it assumes you already got the token and ignores the pin code.

Side note: There is actually a much easier way to set this up now.  [HomeBridgeController](https://github.com/KraigM/homebridgecontroller) now has an 'authorize' button that will do everything for you.  If you've come this far you might as well finish it but if you get sick of it you can use HBC instead.

**Comment by rhapsfx** [comment]
Hi
Thanks for the instructions.
I just did , got redirected to Nest site,authenticate , then browser get redirected to some amazon server and I received this error 
![screen shot 2016-06-14 at 22 19 21](https://cloud.githubusercontent.com/assets/19934846/16060153/4609c67e-327e-11e6-9c0c-948308b6c76b.png)

**Comment by rhapsfx** [comment]
Any idea ?

**Comment by rhapsfx** [comment]
After reconfiguring from scratch. Everything worked

**Comment by mewejo** [comment]
This got me. The example config included an example token. remove it and it'll generate the new token on first run (provided you've added the pin etc)

**Comment by justinshuls** [comment]
Yeah, remove the token line from the config for first run.
