### ISSUE TITLE
Not a valid username

### ISSUE THREAD

**Issue by charlestruluck** [KraigM/homebridge-nest#72]
Hey,
I tried setting this up and I got an error:
```

charles$ homebridge
[8/1/2016, 3:38:22 PM] Loaded plugin: homebridge-nest
[8/1/2016, 3:38:22 PM] Registering platform 'homebridge-nest.Nest'
[8/1/2016, 3:38:22 PM] ---
/usr/local/lib/node_modules/homebridge/lib/server.js:184
      throw new Error('Not a valid username: ' + username + '. Must be 6 pairs of colon-' +
      ^

Error: Not a valid username: undefined. Must be 6 pairs of colon-separated hexadecimal chars (A-F 0-9), like a MAC address.
    at Server._loadConfig (/usr/local/lib/node_modules/homebridge/lib/server.js:184:13)
    at new Server (/usr/local/lib/node_modules/homebridge/lib/server.js:44:23)
    at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:26:16)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.runMain (module.js:575:10)
    at run (bootstrap_node.js:352:7)
    at startup (bootstrap_node.js:144:9)
    at bootstrap_node.js:467:3
```

Anyone know why?

Thanks,
Charles

**Comment by charlestruluck** [comment]
Looking back over the error, I realized it has nothing to do with Homebridge-nest. Sorry!
