### ISSUE TITLE
Cannot read property 'username' of undefined

### ISSUE THREAD

**Issue by rtsmith82** [KraigM/homebridge-nest#76]
I've installed homebridge and configured the config.json as below:

`{
	"platforms": [{
		"platform": "Nest",

		"token": "c.5ABsTpo88k5yfNIxZlh...",

		"clientId": "98e069fc-b133-48ba-bd8a2a1c4",
		"clientSecret": "87EBqoWmP3LHryP",
		"code": "LZGL",

		"username": "username",
            	"password": "password"
	}]
}`

This validates. When I run homebridge from terminal I get the following:

`[9/16/2016, 10:02:43 PM] Loaded plugin: homebridge-nest
[9/16/2016, 10:02:43 PM] Registering platform 'homebridge-nest.Nest'
[9/16/2016, 10:02:43 PM] ---
/usr/local/lib/node_modules/homebridge/lib/server.js:181
  var username = config.bridge.username;
                              ^

TypeError: Cannot read property 'username' of undefined
    at Server._loadConfig (/usr/local/lib/node_modules/homebridge/lib/server.js:181:31)
    at new Server (/usr/local/lib/node_modules/homebridge/lib/server.js:44:23)
    at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:26:16)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:139:18)
    at node.js:974:3
`

**Comment by toshibochan** [comment]
You can't just take this code from exemple and try to connect! 
You did all this step?

How to Setup New API

Go to https://developer.nest.com
Choose Sign In
Use your normal account to sign in
Fill in you info in 'Step 1'
In 'Step 2' set:
Company Name: HomeBridge-Nest
Company URL: https://github.com/kraigm/homebridge-nest
Country: [Your Country]
Size of Company: Individual
Then just agree to the terms and submit
Go to Products and create a new product
Fill in:
Product Name: HomeBridge
Description: Open source project to provide HomeKit integration
Categories: HomeAutomation
Support URL: https://github.com/kraigm/homebridge-nest
Redirect URL: [LEAVE BLANK]
Permissions (minimum):
Enable Thermostat with read/write v4
Enable Away with read/write v2
Enable Smoke+CO alarm with read v4 (if you ever might want Nest Protect)
Enable Camera with read v2 (if you ever might want Nest Cam, motion detection only)
Now you should have a product. Now locate the Keys section on the right of your product's page
Copy the Product ID to your HomeBridge config as the clientId in the Nest config
Copy the Product Secret to your HomeBridge config as the clientSecret in the Nest config
Navigate to the Authorization URL
Accept the terms and copy the Pin Code to your HomeBridge config as the code in the Nest config
Run HomeBridge once (do not include the token in the config at this time) and you should find a log that says something like "CODE IS ONLY VALID ONCE! Update config to use {'token':'c.5ABsTpo88k5yfNIxZlh...'} instead." Copy the c.5ABsTpo88k5yfNIxZlh... portion to your HomeBridge config as the token in the Nest config
You should be able to restart HomeBridge and it should succeed with the new token.
After that you will be FINALLY done (Huzzah!). If the token is working correctly, you no longer NEED the other three configs (clientId, clientSecret, and code) nor the original username and password from the legacy system (but you can keep them around if you wish, they will be ignored).

**Comment by rtsmith82** [comment]
Did all the steps listed. It fails when I do: "Run HomeBridge once (do not include the token in the config at this time) and you should find a log that says something like "CODE IS ONLY VALID ONCE! Update config to use {'token':'c.5ABsTpo88k5yfNIxZlh...'} instead." Copy the c.5ABsTpo88k5yfNIxZlh... portion to your HomeBridge config as the token in the Nest config"

When I run Homebridge I get the error instead of getting the log portion

**Comment by gholevas** [comment]
I'm getting the same error. "Error: Not a valid username: undefined. Must be 6 pairs of colon-separated hexadecimal chars (A-F 0-9), like a MAC address." I followed all of the steps. It is throwing this error whether or not I include a valid username.

**Comment by gholevas** [comment]
you need to put a username in the bridge part of the config

https://github.com/nfarina/homebridge/blob/master/config-sample.json

**Comment by actuarysailor** [comment]
The Setup New API does not work; says product name HomeBridge is already taken.  I think it is because Nest went more cloudy on their API developer tools.
