### ISSUE TITLE
Falling back to legacy API

### ISSUE THREAD

**Issue by maratonat** [KraigM/homebridge-nest#80]
Nest control seems to be work ok, but looking at the error logs, I see that it's falling back to legacy API. Any idea why this might be happening?

{ Error: UNAUTHORIZED: {"error":"unauthorized","type":"https://developer.nest.com/documentation/cloud/error-messages#auth-error","message":"unauthorized","instance":"xxxxxx-xxxx-xxxx-xxxx-xxxxxxxxx"}
       at Error (native)
       at Yg (/usr/local/lib/node_modules/homebridge-nest/node_modules/firebase/lib/firebase-node.js:150:468)
       at Object.Cc (/usr/local/lib/node_modules/homebridge-nest/node_modules/firebase/lib/firebase-node.js:149:255)
       at /usr/local/lib/node_modules/homebridge-nest/node_modules/firebase/lib/firebase-node.js:182:177
       at Rh.h.Jd (/usr/local/lib/node_modules/homebridge-nest/node_modules/firebase/lib/firebase-node.js:186:104)
       at Fh.Jd (/usr/local/lib/node_modules/homebridge-nest/node_modules/firebase/lib/firebase-node.js:176:364)
       at wh.Jg (/usr/local/lib/node_modules/homebridge-nest/node_modules/firebase/lib/firebase-node.js:174:280)
       at zh (/usr/local/lib/node_modules/homebridge-nest/node_modules/firebase/lib/firebase-node.js:168:464)
       at Client.Ka.onmessage (/usr/local/lib/node_modules/homebridge-nest/node_modules/firebase/lib/firebase-node.js:167:321)
       at Client.dispatchEvent (/usr/local/lib/node_modules/homebridge-nest/node_modules/firebase/node_modules/faye-websocket/lib/faye/websocket/api/event_target.js:22:30)
       at Client._receiveMessage (/usr/local/lib/node_modules/homebridge-nest/node_modules/firebase/node_modules/faye-websocket/lib/faye/websocket/api.js:134:10)
       at Client.<anonymous> (/usr/local/lib/node_modules/homebridge-nest/node_modules/firebase/node_modules/faye-websocket/lib/faye/websocket/api.js:34:49)
       at emitOne (events.js:101:20)
       at Client.emit (events.js:188:7)
       at Client.<anonymous> (/usr/local/lib/node_modules/homebridge-nest/node_modules/firebase/node_modules/faye-websocket/node_modules/websocket-driver/lib/websocket/driver/hybi.js:451:14)
       at pipe (/usr/local/lib/node_modules/homebridge-nest/node_modules/firebase/node_modules/faye-websocket/node_modules/websocket-driver/node_modules/websocket-extensions/lib/pipeline/index.js:37:40)
       at Pipeline._loop (/usr/local/lib/node_modules/homebridge-nest/node_modules/firebase/node_modules/faye-websocket/node_modules/websocket-driver/node_modules/websocket-extensions/lib/pipeline/index.js:44:3)
       at Pipeline.processIncomingMessage (/usr/local/lib/node_modules/homebridge-nest/node_modules/firebase/node_modules/faye-websocket/node_modules/websocket-driver/node_modules/websocket-extensions/lib/pipeline/index.js:13:8)
       at Extensions.processIncomingMessage (/usr/local/lib/node_modules/homebridge-nest/node_modules/firebase/node_modules/faye-websocket/node_modules/websocket-driver/node_modules/websocket-extensions/lib/websocket_extensions.js:133:20)
       at Client._emitMessage (/usr/local/lib/node_modules/homebridge-nest/node_modules/firebase/node_modules/faye-websocket/node_modules/websocket-driver/lib/websocket/driver/hybi.js:442:22)
       at Client._emitFrame (/usr/local/lib/node_modules/homebridge-nest/node_modules/firebase/node_modules/faye-websocket/node_modules/websocket-driver/lib/websocket/driver/hybi.js:405:19)
       at Client.parse (/usr/local/lib/node_modules/homebridge-nest/node_modules/firebase/node_modules/faye-websocket/node_modules/websocket-driver/lib/websocket/driver/hybi.js:144:18) code: 'UNAUTHORIZED' },
  isOperational: true,
  code: 'UNAUTHORIZED' }
[9/21/2016, 9:58:06 AM] Falling back to legacy API.

**Comment by maratonat** [comment]
Having re-read the existing issues, I was able to resolve the problem.
However, now I am seeing an error when trying to adjust the thermostat:
FIREBASE WARNING: set at /devices/thermostats/7u3hYcaA_NO...75CZ/target_temperature_f failed: Cannot set %s while mode is %s
